name: flutter_app
description: A new Flutter application for yipli app frontend.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.00+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  adobe_xd: ^2.0.0+1
  async:
  auto_size_text: ^3.0.0-nullsafety.0
  #age: ^0.0.1
  #barcode_scan: ^3.0.1
  bot_toast: ^4.0.1
  #charts_flutter: ^0.10.0
  connectivity: ^3.0.6
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.3
  cupertino_stepper: ^0.2.0
  device_apps: ^2.1.1
  eva_icons_flutter: ^3.0.0
  feature_discovery: ^0.14.0
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  firebase_dynamic_links: ^2.0.6
  firebase_image: ^1.0.1
  firebase_storage: ^8.1.3
  fl_chart: ^0.36.2
  flare_flutter: ^3.0.1
  flare_splash_screen: ^4.0.0
  flip_card: ^0.5.0
  #flushbar: ^1.10.2
  flutter_animator: ^3.1.1
  #flutter_facebook_login: ^3.0.0
  flutter_rating_bar: ^4.0.0
  flutter_staggered_animations: ^1.0.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.0.4
  #grouped_buttons: ^1.0.4
  image_cropper: ^1.4.0
  image_picker: ^0.8.0+3
  intro_slider: ^2.4.3
  introduction_screen: ^2.1.0
  jiffy: ^4.1.0
  #modal_progress_hud: ^0.1.3
  #open_appstore: ^1.0.2
  page_transition: ^2.0.2
  #passwordfield: 0.0.82
  percent_indicator: ^3.0.1
  photo_view: ^0.11.1
  #polygon_clipper: ^1.0.2
  provider: ^5.0.0
  random_string: ^2.2.0-nullsafety
  #responsive_container: ^0.0.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  simple_animations: ^3.1.1
  #string_mask: ^0.1.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.6
  uuid: ^3.0.4
  video_player: ^2.1.6
  package_info: ^2.0.2
  animated_text_kit: ^4.2.1
  scratcher: ^2.1.0
  confetti: ^0.6.0-nullsafety
  #snappable: ^1.0.1
  intl: ^0.17.0
  #slide_countdown_clock: ^1.0.3
  number_slide_animation: ^0.2.1
  html: ^0.15.0
  liquid_pull_to_refresh: ^3.0.0
  just_audio: ^0.7.5
  infinite_listview: ^1.1.0
  responsive_framework: ^0.1.2
  device_info: ^2.0.2
  rive_splash_screen: ^0.1.0
  rive: ^0.7.18
  flushbar: ^1.10.4
  age: ^0.0.1
  modal_progress_hud: ^0.1.3
  barcode_scan: ^3.0.1
  flutter_facebook_login: ^3.0.0
  open_appstore: ^1.0.2
  passwordfield: ^0.0.82
  polygon_clipper: ^1.0.2
  string_mask: ^0.1.0
  responsive_container: ^0.0.1
  slide_countdown_clock: ^1.0.3
  charts_flutter: ^0.10.0
  grouped_buttons: ^1.0.4
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flare/
    - assets/images/mats/
    - assets/images/NewSliderImages/
    - assets/videos/journey/
    - assets/audio/OnBoarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Black.ttf
        - asset: fonts/Lato/Lato-Bold.ttf
        - asset: fonts/Lato/Lato-Light.ttf
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-Thin.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
